### PR TITLE
Fixed semver version syntax in package.json (NPM install fails)

### PR DESCRIPTION
**Pull request by danielweck**
See http://semver.org

### CODE REVIEW

**Comment by pkra** [comment]
Thanks! Would it help if I properly published this?

**Comment by danielweck** [comment]
Readium's build system uses NPM (v2, not v3) to resolve external library dependencies. We use a number of "proper" NPM-hosted packages, in addition to those that are available at GitHub (either because they are not published at NPM, or because we patch them in our own forks). MathJax falls into the latter category :)
So, in all likelihood Readium will continue to fetch MathJax from GitHub. Feel free to publish to NPM, but we probably won't reference the `MathJax.js` lib from there. GitHub gives us more flexibility, e.g. always fetch the tip of the `master` branch (latest checkin in the git commit history), even though the `package.json` version has not changed (which is handy for some libs that are not maintained with proper semver increments).

**Comment by danielweck** [comment]
PS: Readium's build system includes a script ( https://github.com/readium/readium-cfi-js/blob/develop/readium-build-tools/gitHubForksUpdater.js ) that checks for GitHub upstream updates in forked libs (recursively, all the way to the top of the fork hierarchy). Our `npm run prepare` command informs us when an external dependency has been updated in a third-party Git repository, we then easily diff the source tree changes to figure-out whether we can safely include the new code in the Readium app (in which case, we simply merge the upstream updates into our own fork).
For example, I've just done that with MathJax, since you decided merged my pull request: https://github.com/danielweck/MathJax-single-file/commit/48ee22f72d8d6dc0e0cab2411aea379d1d9f7285

**Comment by pkra** [comment]
> which is handy for some libs that are not maintained with proper semver increments

Now who would ever do that? Oh wait... _causes a distraction and quickly runs away_

**Comment by danielweck** [comment]
Haha :) 
Not long ago, one of Readium's library dependencies (hosted at NPM) was updated, and unfortunately it included a breaking API change ... yet its semver package.json version only had a minor increment. Thankfully this was easy to catch as the build was very obviously broken ("compile"-time error). This is much more problematic when there's a runtime API change that doesn't get caught by unit tests / continuous integration checks.

**Pull request merged**
