### PR TITLE
Complete rewrite

### LINKED ISSUE #18: rewrite without grunt
Feels like it's time to revamp it.

### PR DESCRIPTION
**Pull request by pkra**
Resolves #18

### CODE REVIEW

**Comment by pkra** [comment]
I think this is as far as I want ot get just now. Comments welcome.

**Comment by pkra** [comment]
Remaining non-critical issues

* non-default fonts in SVG output will lead to an error because MathJax will still load the TeX fontdata (and fail). Not problematic but annoying.
* TeX input `\require` throws processing errors (but the macros from an extension work fine)

**Comment by pkra** [comment]
Critical issues

* MathML+SVG is broken.

**Comment by dpvc** [comment]
> MathML+SVG is broken.

The main problem is in the order of the font files.  You need to load the `Main.js` file before any of the other ones for a particular font family.  For example, you currently have

```
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/BasicLatin.js',
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/CombDiacritMarks.js',
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/Main.js',
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/Other.js'
```

but it should be

```
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/Main.js',
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/BasicLatin.js',
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/CombDiacritMarks.js',
            '/jax/output/SVG/fonts/TeX/Typewriter/Regular/Other.js'
```

(indeed, you cold move all the `Main.js` files to the top of the list if you wanted).

There is a second issue, which is that the `fontdata.js` itself, already includes a number of the `Main.js` files, so loading them again overwrites the data already there, and that can cause problems.  In the case of SVG with TeX, the two are 

            '/jax/output/SVG/fonts/TeX/Main/Regular/Main.js',

and

            '/jax/output/SVG/fonts/TeX/Math/Italic/Main.js',

so these should be removed from the list.  Which files are included varies from font to font (and output jax to output jax), so you will need to look to see which ones are int he `fontdata.js` files for the different fonts.  You can recognize these based on the presence of lines such as

```
  SVG.FONTDATA.FONTS['MathJax_Main'] = {
    directory: 'Main/Regular',
```

for the `TeX/Main/Regular/Main.js` file.

Note that for HTML-CSS STIX, the only Integral font used is IntegralD, so no need to load the other versions (SM, Up, etc).

**Comment by pkra** [comment]
Thanks so much, Davide!

**Comment by pkra** [comment]
> so you will need to look to see which ones are in the fontdata.js files for the different fonts. 

FWIW, I didn't find any other fontdata.js files (using `SVG.FONTDATA.FONTS\['(.*)'\] = \{` to find them).

**Comment by dpvc** [comment]
It looks like the other web fonts for SVG don't pre-include any of the data (like the hand-made ones for STIX and MathJax TeX fonts).  But the CommonHTML and HTML-CSS output jax do have preloaded ones for their MathJax TeX and STIX fonts.  (Substitute CHTML or HTMLCSS for the SVG.)

**Comment by pkra** [comment]
Thanks! I'll take another look.

**Comment by pkra** [comment]
For the time being, I think this is ready to go.

**Pull request merged**
